# Generated by Django 5.2.17 on 2026-09-20 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('turno', models.CharField(choices=[('diurno', 'Diurno'), ('noturno', 'Noturno')], max_length=10)),
            ],
            options={
                'verbose_name': 'Plantão',
                'verbose_name_plural': 'Plantões',
                'ordering': ['turno', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('patio', 'Pátio'), ('central_radio', 'Central de rádio'), ('servico_rua', 'Serviço de rua')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Posto',
                'verbose_name_plural': 'Postos',
            },
        ),
        migrations.CreateModel(
            name='CicloFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(unique=True)),
                ('meses_disponiveis', models.JSONField(default=list, help_text='Lista dos meses (1-12) disponíveis para escolha. Padrão: março a dezembro.')),
                ('teto_mensal_setor', models.PositiveSmallIntegerField(default=6, help_text='Máximo de pessoas de férias por mês, somando o setor inteiro')),
                ('minimo_habilitados_central', models.PositiveSmallIntegerField(default=6, help_text='Mínimo de funcionários habilitados para a Central de rádio disponíveis por mês')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=10)),
                ('data_formalizacao', models.DateTimeField(blank=True, null=True)),
                ('formalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos_formalizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ciclo de férias',
                'verbose_name_plural': 'Ciclos de férias',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_registro_funcional', models.DateField(help_text='Define a antiguidade para fins de desempate')),
                ('habilitado_central', models.BooleanField(default=False, verbose_name='Habilitado para Central de rádio')),
                ('ativo', models.BooleanField(default=True)),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='ferias.plantao')),
                ('posto_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='ferias.posto')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['data_registro_funcional'],
            },
        ),
        migrations.CreateModel(
            name='AlocacaoFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_alocado', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('auto', 'Auto-alocado'), ('operador', 'Decidido pelo operador'), ('pendente', 'Pendente')], default='pendente', max_length=10)),
                ('motivo', models.CharField(blank=True, choices=[('posto', 'Conflito de posto'), ('teto_setor', 'Teto do setor'), ('habilitados', 'Mínimo de habilitados'), ('outro', 'Outro')], max_length=15, null=True)),
                ('observacao', models.TextField(blank=True, help_text="Obrigatório quando o status é 'Decidido pelo operador'")),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='ferias.cicloferias')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='ferias.funcionario')),
            ],
            options={
                'verbose_name': 'Alocação de férias',
                'verbose_name_plural': 'Alocações de férias',
                'constraints': [models.UniqueConstraint(fields=('funcionario', 'ciclo'), name='unica_alocacao_funcionario_ciclo')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_ferias', to='ferias.funcionario')),
            ],
            options={
                'verbose_name': 'Histórico de férias',
                'verbose_name_plural': 'Históricos de férias',
                'ordering': ['-ano'],
                'constraints': [models.UniqueConstraint(fields=('funcionario', 'ano'), name='unico_historico_funcionario_ano')],
            },
        ),
        migrations.CreateModel(
            name='PostoPlantaoCapacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade', models.PositiveSmallIntegerField(help_text='Quantas pessoas cobrem esse posto nesse plantão ao mesmo tempo')),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades', to='ferias.plantao')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades', to='ferias.posto')),
            ],
            options={
                'verbose_name': 'Capacidade de posto por plantão',
                'verbose_name_plural': 'Capacidades de posto por plantão',
                'constraints': [models.UniqueConstraint(fields=('posto', 'plantao'), name='unica_capacidade_posto_plantao')],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_1', models.PositiveSmallIntegerField(verbose_name='1ª opção')),
                ('mes_2', models.PositiveSmallIntegerField(verbose_name='2ª opção')),
                ('mes_3', models.PositiveSmallIntegerField(verbose_name='3ª opção')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='ferias.cicloferias')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='ferias.funcionario')),
            ],
            options={
                'verbose_name': 'Preferência de férias',
                'verbose_name_plural': 'Preferências de férias',
                'constraints': [models.UniqueConstraint(fields=('funcionario', 'ciclo'), name='unica_preferencia_funcionario_ciclo')],
            },
        ),
    ]
